name: Distribute to Firebase Services

on:
  workflow_dispatch:
    inputs:
      variants:
        description: Select Variant
        required: true
        default: 'debug'
        type: choice
        options:
          - 'debug'
          - 'release'
      release_notes:
        type: string
        required: true
        default: 'Manual Debug Build'
        description: 'Release Notes'
        
jobs:
  collect-reports:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate API Key
        env:
          API_KEY_MEALS: ${{secrets.API_KEY_MEALS}}
          API_KEY_UPLOAD: ${{secrets.API_KEY_UPLOAD}}
        run: |
          echo API_KEY_MEALS=$API_KEY_MEALS > ./local.properties
          echo API_KEY_UPLOAD=$API_KEY_UPLOAD >> ./local.properties

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run : chmod +x gradlew

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'

      - name: Setup Fastlane - with Push
        uses: maierj/fastlane-action@v2.3.0
        with:
          lane: ${{inputs.variants}}

      - name: Upload artifact to Firebase App Distribution - Mode DEBUG
        if: ${{inputs.variants == 'debug'}}
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID_DEBUG}}
          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
          groups: testers
          file: app/build/outputs/apk/${{inputs.variants}}/app-${{inputs.variants}}.apk
          releaseNotes: ${{inputs.release_notes}}

      - name: Upload artifact to Firebase App Distribution - Mode RELEASE UNSIGNED
        if: ${{inputs.variants == 'release'}}
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID_RELEASE}}
          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
          groups: release-unsigned
          file: app/build/outputs/apk/${{inputs.variants}}/app-${{inputs.variants}}-unsigned.apk
          releaseNotes: ${{inputs.release_notes}}
