name: Android with Github Action - CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  collect-reports:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate API Key
        env:
          API_KEY_MEALS: ${{secrets.API_KEY_MEALS}}
          API_KEY_UPLOAD: ${{secrets.API_KEY_UPLOAD}}
        run: |
          echo API_KEY_MEALS=$API_KEY_MEALS > ./local.properties
          echo API_KEY_UPLOAD=$API_KEY_UPLOAD >> ./local.properties

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run : chmod +x gradlew

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'

      - name: Setup Fastlane
        uses: maierj/fastlane-action@v2.3.0
        with:
          lane: 'go'

      - name: Build report Test All Module
        uses: actions/upload-artifact@v3
        with:
          name: report-test
          path: |
            presentation/build/reports,
            domain/build/reports

      - name: Build debug Apks
        uses: actions/upload-artifact@v3
        with:
          name: generate-apks
          path: app/build/outputs/apk
